# Generated by Django 4.0.2 on 2022-02-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldo',
            old_name='valor',
            new_name='value',
        ),
    ]
