# Generated by Django 4.0.2 on 2022-02-24 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
