# Generated by Django 4.0.2 on 2022-02-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Tipo',
        ),
        migrations.RenameModel(
            old_name='Contato',
            new_name='Transacao',
        ),
    ]
