/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import poligonos.Poligonos;

/**
 *
 * @author JP
 */
public class TelaPoligono extends javax.swing.JFrame {
    Poligonos poligono = new Poligonos();
    /**
     * Creates new form TelaPoligono
     */
    public TelaPoligono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bBaseRetangulo = new javax.swing.JButton();
        bPerimetroRetangulo = new javax.swing.JButton();
        bBaseTriangulo = new javax.swing.JButton();
        lResultado = new javax.swing.JLabel();
        tAltura = new javax.swing.JTextField();
        tBase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Altura");

        jLabel2.setText("Base");

        bBaseRetangulo.setText("Area retangulo");
        bBaseRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaseRetanguloActionPerformed(evt);
            }
        });

        bPerimetroRetangulo.setText("Perimetro retangulo");
        bPerimetroRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPerimetroRetanguloActionPerformed(evt);
            }
        });

        bBaseTriangulo.setText("Base triangulo");
        bBaseTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaseTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBaseRetangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPerimetroRetangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBaseTriangulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tAltura)
                            .addComponent(tBase, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaseRetangulo)
                    .addComponent(bPerimetroRetangulo)
                    .addComponent(bBaseTriangulo))
                .addGap(18, 18, 18)
                .addComponent(lResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBaseRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaseRetanguloActionPerformed
        poligono.setAltura(Double.parseDouble(tAltura.getText()));
        poligono.setBase(Double.parseDouble(tBase.getText()));
        poligono.areaRetangulo();
        lResultado.setText(Double.toString(poligono.getResultado()));
    }//GEN-LAST:event_bBaseRetanguloActionPerformed

    private void bPerimetroRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPerimetroRetanguloActionPerformed
        poligono.setAltura(Double.parseDouble(tAltura.getText()));
        poligono.setBase(Double.parseDouble(tBase.getText()));
        poligono.perimetroRetangulo();
        lResultado.setText(Double.toString(poligono.getResultado()));
    }//GEN-LAST:event_bPerimetroRetanguloActionPerformed

    private void bBaseTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaseTrianguloActionPerformed
        poligono.setAltura(Double.parseDouble(tAltura.getText()));
        poligono.setBase(Double.parseDouble(tBase.getText()));
        poligono.areaTriangulo();
        lResultado.setText(Double.toString(poligono.getResultado()));
    }//GEN-LAST:event_bBaseTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPoligono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBaseRetangulo;
    private javax.swing.JButton bBaseTriangulo;
    private javax.swing.JButton bPerimetroRetangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lResultado;
    private javax.swing.JTextField tAltura;
    private javax.swing.JTextField tBase;
    // End of variables declaration//GEN-END:variables
}
